version: "2"
services:
  node:
    image: "node:8"
    user: "root"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/letsencrypt/archives/parityshift.com/fullchain1.pem:/home/node/app/ssl/fullchain.pem
      - /etc/letsencrypt/archives/parityshift.com/privkey.pem:/home/node/app/ssl/privkey.pem
      - ./:/home/node/app
    ports:
       - "443:443"
    command: "npm run serve:ssr"
