version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/letsencrypt/csr:/home/node/app/ssl/csr
      - /etc/letsencrypt/keys:/home/node/app/ssl/keys
      - ./:/home/node/app
    ports:
       - "443:443"
    command: "npm run serve:ssr"
